export const images = {
    logo: "/logo-color.svg",
    "log-black": "/logo-black.svg",
    "header-home": "/background-foreground/headerhome.svg",
    hands: "/assets/glyphs/hand.svg",
    flowers: "/assets/glyphs/flower.svg",
    exc: "/assets/glyphs/exc.svg",
    tape: "/assets/glyphs/tape.svg",
    onboard: "/assets/svgs/onboard.svg",
    onboardHorizontal: "/assets/svgs/onboardhor.svg",
    providerHome: "/assets/svgs/providerhome.svg",
    designer: "/assets/svgs/designer.svg",
    daemon: "/assets/svgs/daemon.svg",
    here: "/assets/svgs/here.svg",
    rentHome: "/assets/svgs/rent.svg",
    machineAdd: "/assets/svgs/machineadd.svg",
};
